name: base
channels:
  - conda-forge
dependencies:
- jupyterlab=3.1
- jupyter-offlinenotebook=0.2
- nodejs=12
- nbconvert=6
# RTC
- jupyterlab-link-share=0.2
# Python Kernel
- ipykernel=5.1
- xeus-python=0.9
- ipywidgets=7.6
- widgetsnbextension=3.5
- ipyleaflet=0.13
+- ifcopenshell-
- pandas=1
- python=3.7
